---

scenario:
  test_sequence:
    - lint
    - syntax
platforms:
  - name: instance
    image: centos:7
driver:
  name: docker
lint:
  name: yamllint
provisioner:
  name: ansible
  lint:
    name: ansible-lint
