---
scenario:
  name: default
  test_sequence:
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - check
    - cleanup
    - destroy
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: localhost/centos7
    dockerfile: Dockerfile-Centos7
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
